# src/main/resources/application.yml
server:
  port: ${PORT:8083}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://blogForm_currentcap:fccdc7d446a48e93af0912a44b9ee439bf26d2b0@i9egt.h.filess.io:27018/blogForm_currentcap?connectTimeoutMS=30000&socketTimeoutMS=30000&serverSelectionTimeoutMS=30000}
   
  application:
    name: blog-form-api


  security:
    user:
      name: ${API_USERNAME:user}   # Definir usuario desde variable de entorno con un valor por defecto
      password: ${API_PASSWORD:password}   # Definir contraseña desde variable de entorno con un valor por defecto    

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
  api-docs:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always



